### ISSUE TITLE
missing functions

### ISSUE THREAD

**Issue by david76fr** [cclab-brca/brcarepred#1]
Dear developpers,
The git is very useful but there are missing pieces within the R files (see below). Could you please let me know where the package/functions could be found?
library(brcarepredDEV)
library(brcarepred)
getProbsDR
getProbsLR
getProbsS
Thank you for your help
Best regards,
David

**Comment by oscar-rueda** [comment]
Hi David,

Thanks a lot for your interest in our code.
getProbsDR
getProbsLR
getProbsS
are functions from the package brcarepred (also in the git; file
brcarepred_1.2.tar.gz
<https://github.com/cclab-brca/brcarepred/blob/master/brcarepred_1.2.tar.gz>).
You should install this package first.
The package brcarepredDEV is not needed. What is file where you found that
call, so I can correct it?

Best,
Oscar

**Comment by david76fr** [comment]
Thank you Oscar for your quick reply. I really appreciate. Perfect I was able to install the package. I found the brcarepredDEV in the file 5.ComputeProbsModelER.R.
Have a great day
David
